LNX-137 Add tooltips
group-project-gut/lynx-frontend-godot pull request #13
Opened 2023-05-16 18:59 UTC by filip-szweda

2023-05-16 19:32 UTC, Krystian030 approved these changes

2023-05-17 23:40 UTC, alpinus4 requested changes
Good work overall :)
I really like the tooltips logic as well as  `push_error()` refactor and removing `set_attribute()`.

2023-05-17 23:40 UTC, alpinus4 commented on entity/action/remove_object/RemoveObject.gd
> +	var object_to_remove = world_updater.get_object_by_id(self._object_id)
All the objects are inside objects_container, so we shouldn't check inside `world_updater`

2023-05-17 23:40 UTC, alpinus4 commented on entity/action/remove_object/RemoveObject.gd
> +		self.objects_container.remove_child(object_to_remove)
`objects_container` does not exist

2023-05-17 23:40 UTC, alpinus4 commented on scene.tscn
> +[node name="Camera2D" type="Camera2D" parent="TileMap"]
Why move camera inside TileMap, i see no reason to do so
It's not a component of tilemap

2023-05-17 23:40 UTC, alpinus4 commented on scene/TooltipsUpdater.gd
> +		var object_name = object.get_name().lstrip("@").rstrip("0123456789@")
I don't like the idea that we don't set ID's as names.
Then we have to do shenanigans as this one.

Instead I would like to see here just `object._name`

Then you can change Object.gd to something like this. Works like a charm and it is much cleaner.
![image](https://github.com/group-project-gut/lynx-frontend-godot/assets/25907897/34870e9e-ef3b-4e9c-ad27-1b09ae0f65e9)

2023-05-17 23:40 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +			var object = world_updater.get_object_by_id(entity._object_id)
let's revert to previous logic with names being set to ID's.
Then we don't need this custom function for accessing objects by ID.

2023-05-17 23:40 UTC, alpinus4 commented on scene/world_updater/WorldUpdater.gd
> +func get_objects_by_position(position: Vector2):
I like the idea.
However please move this function to `ObjectsContainer.gd` (we need new script)
Also because it starts to get cumbersome to access ObjectsContainer and WorldUpdater
I would prefer to add them to globals
```gdscript
var WORLD_UPDATER: Node 
var OBJECTS_CONTAINER: Node
```

Then we could add to the WorldUpdater.gd
```gdscript
func _ready():
	Globals.TILE_SIZE = tilemap.tile_set.tile_size
        Globals.WORLD_UPDATER = self
        Globals.OBJECTS_CONTAINER = objects_container
	self.state_getter = get_node("StateGetter")
```

2023-05-18 00:06 UTC, alpinus4 commented
I added tile highlighting
![image](https://github.com/group-project-gut/lynx-frontend-godot/assets/25907897/899c47b7-56bf-449d-9848-73e97cc0576e)

2023-05-18 05:49 UTC, Krystian030 approved these changes
I also have some ideas for the future.
First, we can select (maybe right-click) an agent and then the camera will follow it and second ide is when we click on the agent we can see it's code.

2023-05-18 05:49 UTC, Krystian030 commented on entity/action/remove_object/RemoveObject.gd
> +	var object_to_remove = world_updater.get_object_by_id(self._object_id)
@filip-szweda Why can't we use an object container instead of a world updater?

2023-05-18 05:49 UTC, Krystian030 approved these changes
I also have some ideas for the future.
First, we can select (maybe right-click) an agent and then the camera will follow it and second ide is when we click on the agent we can see it's code.

2023-05-18 05:58 UTC, filip-szweda commented on entity/action/remove_object/RemoveObject.gd
> +	var object_to_remove = world_updater.get_object_by_id(self._object_id)
In `Object.gd` I've deleted:
```
# all objects are identified by their unique id
self.set_name(str(self._id))
```
This means that we can no longer directly access objects in `objects_container` using `.get_node(<id>)`.
I've done it, because object name change to object's id was a hack on my side and it used to-be deprecated `_post_populate()`.
Now we have a unified way of accessing objects in `objects_container` - using `world_updater` helper functions `get_object_by_id`, `get_objects_by_id`, possibly more in the future.

2023-05-18 06:00 UTC, filip-szweda commented on entity/action/remove_object/RemoveObject.gd
> +		self.objects_container.remove_child(object_to_remove)
I will add `remove_object_by_id` to `world_updater`

2023-05-18 06:01 UTC, filip-szweda commented on scene.tscn
> +[node name="Camera2D" type="Camera2D" parent="TileMap"]
It seems that Godot has cached some trash change that I've accidentally commited 🙄

2023-05-18 14:28 UTC, filip-szweda commented on entity/action/remove_object/RemoveObject.gd
> +	var object_to_remove = world_updater.get_object_by_id(self._object_id)
As discussed on Discord, decided to bring back naming objects by id and create a wrapper for `.get_node(<id>)`.

2023-05-18 16:19 UTC, alpinus4 requested changes

2023-05-18 16:19 UTC, alpinus4 commented on scene/ObjectsContainer.gd
> +	return Globals.WORLD_UPDATER.objects_container.get_node(str(id))
`get_node(str(id))`

2023-05-18 16:19 UTC, alpinus4 commented on scene/ObjectsContainer.gd
> +	var object = Globals.WORLD_UPDATER.objects_container.get_node(str(id))
`get_node(str(id))`

2023-05-18 16:19 UTC, alpinus4 commented on scene/ObjectsContainer.gd
> +		Globals.WORLD_UPDATER.objects_container.remove_child(object)
`remove_child(object)`

2023-05-18 16:19 UTC, alpinus4 commented on scene/ObjectsContainer.gd
> +	for object in Globals.WORLD_UPDATER.objects_container.get_children():
`for object in get_children()`

2023-05-18 16:19 UTC, alpinus4 commented on entity/Entity.gd
> +@onready var type = get_name()
let's name it `_type`

2023-05-18 16:19 UTC, alpinus4 commented on entity/action/push/Push.gd
> +@onready var entity_mapper = get_node("/root/Scene/WorldUpdater/StateGetter/EntityDeserializer/EntityMapper")
Lets use World Updater from Globals

2023-05-18 16:19 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +@onready var global_action_queue = get_node("/root/Scene/WorldUpdater/GlobalActionQueue/Queue")
DeltasApplier is inside WorldUpdater
Therefore please use `get_owner()` here as before
Also setting `objects_container` variable was okay as it was before

2023-05-18 16:19 UTC, alpinus4 commented on scene/world_updater/SceneRecreator.gd
> -@onready var objects_container = get_owner().objects_container
i don't like the change to globals, we are inside WorldUpdater
`get_owner()` is more appropriate

2023-05-18 16:19 UTC, alpinus4 commented on scene/world_updater/SceneWiper.gd
> -@onready var objects_container = get_owner().objects_container
Same as before
Inside WorldUpdater, use `get_owner()` as before

2023-05-18 16:19 UTC, alpinus4 commented on scene/world_updater/SceneWiper.gd
> +		Globals.WORLD_UPDATER.objects_container.remove_object_by_id(object._id)
Lets not use this helper function.
It just adds complexity.
We already have the `object` we want to remove, but the helper function attempts to find it again by ID.
`var object = Globals.WORLD_UPDATER.objects_container.get_node(str(id))`
It takes more time.

2023-05-18 16:50 UTC, alpinus4 approved these changes

2023-05-18 16:50 UTC, merged