LNX-153 Add better http request error handling on the godot side handle timeouts
group-project-gut/lynx-frontend-godot pull request #25
Opened 2023-06-20 14:26 UTC by filip-szweda

2023-06-21 12:04 UTC, filip-szweda commented on scene/world_updater/DeltasApplier.gd
> +				Globals.OBJECTS_IN_CREATION.append(object_in_creation["attributes"]["id"])
Rename to `BUSY_OBJECTS`

2023-06-21 12:04 UTC, filip-szweda commented on scene/world_updater/DeltasApplier.gd
>  			if not "_object_id" in entity:
Check `Action` type instead

2023-06-22 07:01 UTC, filip-szweda commented on scene/world_updater/DeltasApplier.gd
> +				await get_tree().create_timer(0.01).timeout
May add up to `0.01s` to created object's desynchronisation, should be checked immediately instead.

2023-06-23 21:56 UTC, alpinus4 requested changes

2023-06-23 21:56 UTC, alpinus4 commented on globals.gd
> +var OBJECTS_IN_CREATION: Array[float] = []
PENDING_OBJECTS_TO_BE_CREATED

2023-06-23 21:56 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +			while(entity._object_id in Globals.OBJECTS_IN_CREATION):
let's move the waiting logic into `objects_container.get_object_by_id` function, and await it when we call it.
It **should always** wait for objects to be created.

Also with that addition it might be safe to remove the retry logic from push (there was an issue with nonexisting objects we wanted to push)
![image](https://github.com/group-project-gut/lynx-frontend-godot/assets/25907897/538e3547-e8e7-4997-bbc0-152fb3975cbc)

2023-06-23 21:56 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +	_speed_up_actions_after_lag(current_tick_number, response["tick_number"])
what if we got a problem with neither `"scene"` nor `"deltas"` being in `response.keys()`
The current_tick_number will be set to `null` or it will crash idk.

It is a change in logic, please handle such case.

2023-06-23 21:56 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +	for object in Globals.WORLD_UPDATER.objects_container.get_children():
it's a costly operation
please check previous `Globals.ACTION_SPEED_MULTIPLIER`
and only if it changed, then set it in all objects

2023-06-23 21:56 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +				await get_tree().create_timer(0.01).timeout
we can await next frame :)
It's just one check in `while` loop every frame, shouldn't be that bad

`await get_tree().process_frame`

2023-06-24 00:25 UTC, EasyJB requested changes
Looking ok, but I would apply some changes. Also before merging, we should change the type of stone and rock as it was done for `log`.

2023-06-24 00:25 UTC, EasyJB commented on scene/MapPopulator.gd
> +	if post_populate_http_request.get_http_client_status() not in [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]:
same comment as above

2023-06-24 00:25 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +		var error = get_state_http_request.request(Globals.SERVER_ADDRESS + "?tick_number=" + str(current_tick_number))
Is `error` correct variable name, when we get response from server?

2023-06-24 00:25 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +	for object in Globals.WORLD_UPDATER.objects_container.get_children():
Imo +1, we should only call this `for` loop, if we have change in speed.

2023-06-24 09:27 UTC, Krystian030 approved these changes

2023-06-24 09:27 UTC, Krystian030 commented on entity/object/Object.gd
> +	tween.tween_property(self, "position", target_position, duration / Globals.ACTION_SPEED_MULTIPLIER).set_trans(Tween.TRANS_LINEAR)
Could you assing `duration / Globals.ACTION_SPEED_MULTIPLIER`  to variable for better readability?

2023-06-24 09:27 UTC, Krystian030 commented on scene/AgentCreator.gd
> +	if post_agent_http_request.get_http_client_status() not in [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]:
Move ` [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]` to variable e.g. allowed_statuses

2023-06-24 14:40 UTC, alpinus4 commented on globals.gd
> +var OBJECTS_IN_CREATION: Array[float] = []
ACK

2023-06-24 14:42 UTC, alpinus4 commented on entity/object/Object.gd
> +	tween.tween_property(self, "position", target_position, duration / Globals.ACTION_SPEED_MULTIPLIER).set_trans(Tween.TRANS_LINEAR)
Let's leave it as is
`0.4` is ambiguous value smaller than `0.5`
It could be `0.45` as well.
`move` should be a generic function that only provides move functionality, so it's better if we move such info outside of it.

I would want to see the duration being set in `move` action, `push` action, etc, to be closely related to the duration of `ExecuteActionTimer`.
like being a few milliseconds less

2023-06-24 14:45 UTC, alpinus4 commented on scene/AgentCreator.gd
> +	if post_agent_http_request.get_http_client_status() not in [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]:
We shouldnt have here any errors, such as handshake error, connection error, cant connect, cant resolve, disconnected
In such case it's the best course of action to ignore it and retry. (Maybe print error for the user in the future)

2023-06-25 09:52 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +	_speed_up_actions_after_lag(current_tick_number, response["tick_number"])
We are only ever getting either `"scene"` or `"deltas"` in `response.keys()`.
If neither of them can be found, it means one of two options:
a) `scene-host` API has been changed and `godot-frontend` has to be adapted (not a matter of this story)
b) we have got an error response that will not get past `response_code == 200` (we are safe)

2023-06-25 23:16 UTC, alpinus4 requested changes
Looks good, just one small thing :)

2023-06-25 23:16 UTC, alpinus4 commented on entity/object/Object.gd
> +	var duration = Globals.DEFAULT_ACTION_SPEED - 0.1 / Globals.ACTION_SPEED_MULTIPLIER
Please move the duration outside of this function, so that it is passed as parameter, similar to as it was before.
I can imagine we could want to for example create some effect which would require moving object two times in one `action execute time`.

Let's treat this function as generic function for moving object with some not known duration.

2023-06-26 18:22 UTC, filip-szweda commented on scene/world_updater/DeltasApplier.gd
> +	if entity._type == "CreateObject":
`entity._type`, but it should be `CreateObject`.

2023-06-26 19:39 UTC, alpinus4 approved these changes
Looks good to me
just caught a one small thing :)

2023-06-26 19:39 UTC, alpinus4 commented on entity/action/move/Move.gd
> +	await object.move(Vector2i(object._position) + Vector2i(self._direction), Globals.DEFAULT_ACTION_SPEED - 0.1 / Globals.ACTION_SPEED_MULTIPLIER)
Please add parenthenesis  `(Globals.DEFAULT_ACTION_SPEED - 0.1) / Globals.ACTION_SPEED_MULTIPLIER`

2023-06-26 19:39 UTC, alpinus4 commented on entity/action/push/Push.gd
> +			await pushed_object.move(Vector2i(pushed_object._position) + Vector2i(self._direction), Globals.DEFAULT_ACTION_SPEED - 0.1 / Globals.ACTION_SPEED_MULTIPLIER)
same as before

2023-06-26 20:31 UTC, EasyJB approved these changes

2023-06-26 20:32 UTC, merged