Lnx 164 equally synchronise players relative to server
group-project-gut/lynx-frontend-godot pull request #28
Opened 2023-07-11 21:36 UTC by EasyJB

After testing I found out that this sollution is most consistent. Max range of gets is about 0.15s (Still lag for 0.8 sec appear but is repaired after 3 ticks (2/3 is the best number here, because when I wanted to synchronise each tick, then it didn't work so good :( )). `Gets` on scene host appear after 0.02s. All in all, lags still show up, but more rarely than before this bugfix implementation

2023-07-12 19:27 UTC, alpinus4 requested changes
git commit messages contain two parts:
- short summary (usually less than 50 characters),
- longer description with lines of 72 characters in length.

Please see: https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

2023-07-12 19:27 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +		if current_tick_number % 3 == 0:
it won't work if we finally decide to change tick_number into hash

2023-07-12 19:27 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
it's not a difference, just current time in ms
`get_unix_time_from_system()` returns current unix time in seconds UTC
```gdscript
var current_time_ms = Time.get_unix_time_from_system()*1000
```

2023-07-12 19:27 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +			var delay_time = 0 if (float(int(difference_in_time) % 1000)) / 1000 < self.acceptable_delay else (float(int(difference_in_time) % 1000)) / 1000
we cannot compute delay from this
basically `difference_in_time` is in a form:
`XXXXXXX000`
where `X` is a digit `0-9`, and this digits represent current unix time UTC.
doing `mod 1000` on this **will always** return 0.

2023-07-12 19:27 UTC, alpinus4 commented on entity/object/agent.gdshader
> +shader_type canvas_item;
shouldn't be here

2023-07-12 19:27 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +var acceptable_delay: float = 0.01
we should probably measure "average" delay between server and client (time for packet to travel both ways)
and base our acceptable delay on this

2023-07-12 21:04 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
Yes, but we also care about ms

2023-07-12 21:09 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +		if current_tick_number % 3 == 0:
It can be random accumulator for this.

2023-07-12 21:10 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +			var delay_time = 0 if (float(int(difference_in_time) % 1000)) / 1000 < self.acceptable_delay else (float(int(difference_in_time) % 1000)) / 1000
Nah, `difference_in_time`  is in ms, because `get_unix_time_from_system` returns XXXXXX.XXX

2023-07-12 21:15 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +var acceptable_delay: float = 0.01
Okay debatable.

2023-07-12 21:18 UTC, EasyJB commented
In general logic for this sollution is to be as close to full second as possible

2023-07-13 07:54 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +			var delay_time = 0 if (float(int(difference_in_time) % 1000)) / 1000 < self.acceptable_delay else (float(int(difference_in_time) % 1000)) / 1000
Ack

2023-07-13 07:54 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
Ack

2023-07-13 07:55 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
Please change var name then, it's misleading

2023-07-13 07:56 UTC, alpinus4 commented
> In general logic for this sollution is to be as close to full second as possible

What if scene-host is as far from second as possible
It's not guaranteed scene-host is close
And we shouldn't assume that

2023-07-13 10:44 UTC, EasyJB commented
But our ticks are based on gets, when I was trying to base it on last send tick timestamp, the results were awful. Maybe we cannot interfere to scene-host, but if all clients will tick in similair time, they should get same scene to display in almost the same time.

2023-07-13 20:48 UTC, filip-szweda requested changes

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +var get_state_wait_time: float = 1.0
Move to `globals.gd` and rename to `DEFAULT_GET_STATE_WAIT_TIME`

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +			get_node("GetStateTimer").wait_time = 1
Instead of `1` use `DEFAULT_GET_STATE_WAIT_TIME` from `globals.gd`

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +		if current_tick_number % 3 == 0:
Why do we synchronise every 3 ticks and not every tick?

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
Also, add space before and after `*` sign

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +			var difference_in_time = Time.get_unix_time_from_system()*1000
I also like `current_time_ms`

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +var acceptable_delay: float = 0.01
No need for this variable to be global. Also, it is a constant variable, rename it to `ACCEPTABLE_DELAY` and use `const` instead of `var`

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +			var delay_time = 0 if (float(int(difference_in_time) % 1000)) / 1000 < self.acceptable_delay else (float(int(difference_in_time) % 1000)) / 1000
Break this into multiple lines:
```
var delay = (float(int(difference_in_time) % 1000)) / 1000
if delay < self.ACCEPTABLE_DELAY:
   delay = 0
const WAIT_TIME_DELAY = delay if delay < 0.85 else -(1 - delay)
get_node("GetStateTimer").wait_time = DEFAULT_GET_STATE_WAIT_TIME - WAIT_TIME_DELAY 
```
^ could be improved, still

2023-07-13 20:48 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +
What was the motivation of not using `tick_timestamp` from the server?

2023-07-13 20:53 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +		if current_tick_number % 3 == 0:
When I tried to synchronise it every tick, I got huge bias. It was random.

2023-07-13 20:56 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +		if current_tick_number % 3 == 0:
Ok. Interesting

2023-07-13 20:59 UTC, EasyJB commented on scene/world_updater/StateGetter.gd
> +
Actually it didn't synchronise, I think because of `background_task` .

2023-07-13 21:15 UTC, alpinus4 commented
> But our ticks are based on gets, when I was trying to base it on last send tick timestamp, the results were awful. Maybe we cannot interfere to scene-host, but if all clients will tick in similar time, they should get same scene to display in almost the same time.

They are based on GETs but it doesn't indicate anything
We could change the underlying implementation of tick triggering to be more reliable and not depend on GETs in any way.

```python
async def tick_trigger():
    if time.time() - state.last_tick_time >= 1:
        await tick()
        state.last_tick_time = time.time()
```
The implementation of tick trigger isn't aligned in any way to whole seconds.

Therefore while your solution might reduce lags (the worst scenario is when ticks are always triggered halfway between seconds, so we delay of 0.5s + delay of sending and receiving packet)

It's not the right way to do it in my opinion, and it's still flawed.

### Recommendation

The best way would be to get last tick timestamp from scene-host as you did before.
It didn't work beacuse it looked like that:
```gdscript
var difference_in_time = (Time.get_unix_time_from_system() - float(response["tick_timestamp"]))*1000
self.get_node("GetStateTimer").wait_time = 1 - (float(int(difference_in_time) % 1000)) / 1000
var delay_time = 0 if (float(int(difference_in_time) % 1000)) / 1000 < acceptable_delay else (float(int(difference_in_time) % 1000)) / 1000
self.get_node("GetStateTimer").wait_time = 1 - delay_time
```
If I correctly understand the logic
It would take the `difference_in_time` and check if it is acceptable
if it is not acceptable then we wait remainder to whole second from last tick
and at this time another tick should happen on the server so we then perform GET 

**HOWEVER**
this solution is flawed because it doesn't take into account that 
the fact that we are desynchronized is probably because of the time it takes for request to travel from client to server.
And the time for packets to travel from client to server (the actual physical delay)
is not taken into account.

Ideally the GET request should be sent from client before actual tick on the server, so that the request arrives from client to server right after actual tick
Then server replies
And our delay is equivalent to _time of packet travel from server to client_
We could denote this time as _X_
And _1X_ delay is the smallest delay we could get and we should aim for it

2023-07-13 21:20 UTC, alpinus4 commented on scene/world_updater/StateGetter.gd
> +
> Actually it didn't synchronise, I think because of `background_task` .

The `background_task` is just a way to check and run ticks
it might not be the best solution for scene-host because the time between ticks is not entirely consistent
(that's why in the future ticks in scene-host should be triggered in different way)

However
It shouldn't matter for frontend in which way the ticks are triggered on server, or if the time between ticks is consistent on server or not
It didn't synchronize, but `background_task` wasn't the reason

2023-07-13 23:22 UTC, EasyJB commented
> this solution is flawed because it doesn't take into account that
> the fact that we are desynchronized is probably because of the time it takes for request to travel from client to server.
> And the time for packets to travel from client to server (the actual physical delay)
> is not taken into account.
Bus as far as I checked locally the average time of travel is 0.02 sec.  And actually imo it's imposssible to reduce this lag, because one packet can transfer in 0.5 and next in 0.02 sec. So we cannot predict this time. If I got this problem locally, for sure we will have it with cluster. 

> deally the GET request should be sent from client before actual tick on the server, so that the request arrives from client to server right after actual tick
Yes, but what if something wrong happened and packet was transfered in 0.5 sec not in 0.02. Also what if tick travels right before tick trigger and it won't get new tick, but just the previous one (in this scenario we are tick behind.

2023-08-07 17:36 UTC, closed without merging