LNX-186 Player must be able to remove agents
group-project-gut/lynx-frontend-godot pull request #37
Opened 2023-08-26 20:38 UTC by Krystian030

2023-08-27 16:08 UTC, filip-szweda requested changes

2023-08-27 16:08 UTC, filip-szweda commented on entity/object/agent/Agent.gd
> +			agent_options.on_agent_clicked(self._id)
Maybe we could rename `on_agent_clicked` to `show_panel` (similarly to `hide_panel`)?

2023-08-27 16:08 UTC, filip-szweda commented on entity/object/agent/Agent.gd
> +func _input(event):
From what I understand, now every `Agent` listens for mouse right click event and then decides if it was them that was clicked or not.

If possible, it would be more efficient and lofical to have only UI listen for this event, finding appropriate `Agent` and then opening up the panel. Call me on Discord if you would want to discuss that.

2023-08-28 10:08 UTC, EasyJB commented
I found problem, that you can only delete agent which was firstly created. So if you create agent A, then B you can only delete A.

2023-08-31 20:29 UTC, filip-szweda approved these changes

2023-08-31 20:33 UTC, merged