LNX-181 Distinguish agents
group-project-gut/lynx-frontend-godot pull request #38
Opened 2023-08-26 22:21 UTC by Krystian030

A border has been created for agents. The dark blue agent's border indicates our agent, while the red border indicates the agents of other players
![image](https://github.com/group-project-gut/lynx-frontend-godot/assets/101421631/ba31ff79-2de1-4c5f-8d28-5efccc26680f)

2023-08-27 09:46 UTC, filip-szweda commented
1. Each Player should have their own color e.g. there are 3 players → Player No. 1 has Red Agents, Player No. 2 has Blue Agents, Player No. 3 has Green Agents. We could very easily generate Player's color based on Player's ID.
2. There's a very useful `CanvasItem` property called `modulate` that could be used to color Agents e.g.:
![obraz](https://github.com/group-project-gut/lynx-frontend-godot/assets/68189467/da095df5-62e8-4e53-b7f0-466ca696598d)

2023-08-27 09:48 UTC, filip-szweda requested changes
Please consider https://github.com/group-project-gut/lynx-frontend-godot/pull/38#issuecomment-1694621868

2023-08-27 15:52 UTC, filip-szweda requested changes

2023-08-27 15:52 UTC, filip-szweda commented on entity/object/agent/Agent.gd
> +@onready var _border = get_node("Border")
You can declare `_border` and `_sprite` in `_ready` function (without `_` in their names of course), since they're not used anywhere else

2023-08-27 15:52 UTC, filip-szweda commented on entity/object/agent/Agent.gd
> +	if agent_id == self._id:
What is this for? Can we not just return `Color(r, g, b)` at this point?

2023-08-27 15:52 UTC, filip-szweda commented on entity/object/agent/Agent.gd
> +	var hashed_id = hash(agent_id)
`hashed_id` is not used anywhere

2023-08-28 12:40 UTC, EasyJB approved these changes
Imo looking ok, but once I (when I firstly opened app) one of my agents was  purely black, so idk if my files didn;t reload, or it's a bug.

2023-08-28 12:40 UTC, EasyJB commented on entity/object/agent/Agent.gd
> +	if agent_id == self._id:
Imo its used to slighty change colour

2023-08-31 18:56 UTC, filip-szweda approved these changes
We consistently use 1 empty line between functions throughout this project, so I would recommend doing that here as well.

2023-08-31 19:09 UTC, merged