LNX-140-Add-audio-effects
group-project-gut/lynx-frontend-godot pull request #39
Opened 2023-08-27 12:57 UTC by EasyJB

Add background music, move effect, pressing button sound. If our speed needs to be changed

2023-08-27 13:12 UTC, Krystian030 approved these changes

2023-08-27 13:12 UTC, Krystian030 commented on entity/action/move/Move.gd
> +		object.get_node("AnimationEffect").stream = load("res://assets/Music/walking.wav")
W sumie może warto przenieść to ładowanie do metody `_ready` czy coś, żeby nie ładować tego samego z każdym wywołaniem akcji

2023-08-27 13:12 UTC, Krystian030 commented on entity/action/error_log/ErrorLog.gd
> +	audio.stream = load("res://assets/Music/error_message.wav")
W sumie może warto przenieść to ładowanie do metody _ready czy coś, żeby nie ładować tego samego z każdym wywołaniem akcji

2023-08-27 13:12 UTC, Krystian030 commented on entity/action/print/Print.gd
> +	var audio = get_node("/root/Scene/AudioEffect")
W sumie może warto przenieść to ładowanie do metody _ready czy coś, żeby nie ładować tego samego z każdym wywołaniem akcji

2023-08-28 11:22 UTC, filip-szweda requested changes

2023-08-28 11:22 UTC, filip-szweda commented on scene/world_updater/StateGetter.gd
> +			object.get_node("AnimationEffect").pitch_scale = Globals.ACTION_SPEED_MULTIPLIER
Why `AnimationEffect`? Shouldn't this be called `SoundEffect`?

2023-08-28 11:22 UTC, filip-szweda commented on config.gd
> +const DEFAULT_ACTION_AUDIO: float = 1.0
By occasion, could you please move:
```
var SERVER_ADDRESS: String = "http://127.0.0.1:8555/" # localhost by default, to be changed later
var DEFAULT_ACTION_SPEED: float = 0.5
var BUSY_HTTP_STATUSES: Array[int] = [HTTPClient.STATUS_CONNECTING, HTTPClient.STATUS_REQUESTING]
```
from `globals.gd` to `config.gd` and make them `const`? These values are configurable.

2023-08-28 11:22 UTC, filip-szweda commented on entity/action/error_log/ErrorLog.gd
> +	var audio = get_node("/root/Scene/AudioEffect")
In `Action.gd` you can add:
```
func _play_audio(effect):
   var audio = get_node("/root/Scene/AudioEffect")
   audio.stream = effect
   audio.play()
```
and call it here, in `Move`, `Print` etc.

2023-09-01 18:33 UTC, filip-szweda commented
Move sound is delayed by about 8 seconds and ends rather abruptly

2023-10-06 19:41 UTC, closed without merging