Lnx 140 add audio effects
group-project-gut/lynx-frontend-godot pull request #53
Opened 2023-10-04 21:25 UTC by EasyJB

2023-10-05 16:44 UTC, filip-szweda requested changes

2023-10-05 16:44 UTC, filip-szweda commented on Camera2D.gd
> +
🤨

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +	var screen_size = Vector2i(1280, 720) / camera.zoom.x /2
You can use `screen_get_size` from https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-screen-get-size

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/action/Action.gd
> +func play_global_action(effect):
Specify `effect` type

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +func play_audio(effect, obj_position):
Specify `effect` and `obj_position` types

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +@onready var camera = get_node("/root/Scene/Camera2D")
Add an empty line between this variable declaration and following function definition

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +#Function used to play sound around agents, like sound animation of action
IMO `play_audio` is clear enough and this comment is not needed

2023-10-05 16:44 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +	if obj_position.x + 8 < camera.position.x + screen_size.x and \
Please, put 8 and 11 into variables

2023-10-05 16:44 UTC, filip-szweda commented on entities/objects/player_objects/agents/agent.tscn
> +[node name="SoundEffect" type="AudioStreamPlayer2D" parent="."]
To `res://addons/gut/lynx_nodes/entity/object/player_object/agent/Agent.gd` add something like:
```
func _setup_audio_stream_player_2d():
	self.audio_stream_player_2d = AudioStreamPlayer2D.instantiate()
	self.add_child(self.audio_stream_player_2d )
```
to `res://addons/gut/lynx_nodes/nodes/LynxAgentNode.gd` something like:
```
@tool
extends LynxAgent

var action_queue: Node
var execute_action_timer: Timer
var speech_bubble: Control
var audio_stream_player_2d: AudioStreamPlayer2D

@export var action_speed: float

func _enter_tree():
	_setup_action_queue()
	_setup_execute_action_timer()
	_setup_speech_bubble()
        _setup_audio_stream_player_2d
```
then you should be able to use `audio_stream_player_2d` instead of creating `@onready var _audio_node = get_node("SoundEffect")`.

2023-10-05 23:07 UTC, filip-szweda commented on addons/lynx_nodes/entity/object/player_object/agent/Agent.gd
> +	var square_offset = 8 # Size of square = 16
This is OK for now, but we will need to add a global variable for sprite size in the future.
In some places where sprite size was needed, `get_width()` was used, but as shown here this is clearly not viable, because we  have a logical connection to any specific texture.

2023-10-05 23:08 UTC, filip-szweda approved these changes
It would be nice if you could consider https://github.com/group-project-gut/lynx-frontend-godot/pull/53#discussion_r1347710113, but otherwise LGTM

2023-10-06 06:49 UTC, Krystian030 approved these changes

2023-10-06 14:06 UTC, merged