[WiP] Allow multiplayer.
group-project-gut/lynx-frontend-godot pull request #8
Opened 2023-05-05 09:35 UTC by alpinus4

Ticker is disabled.
Additionally there has to be added global action queue with addObject action handling.
To be added later.

2023-05-16 16:09 UTC, alpinus4 commented
GlobalActionQueue was added by @Krystian0130 
I fixed add agent button, now adding agent is entirely handled by deltas.

2023-05-16 16:26 UTC, filip-szweda requested changes

2023-05-17 23:42 UTC, alpinus4 commented on scene/world_updater/AgentCreator.gd
>  	create_agent(code, position)
Currently it is exactly like the second option

```gdscript
var new_agent = Agent.instantiate()
new_agent.init(_position, _id, _owner, _code)
post_agent(new_agent)
new_agent.queue_free()
```

2023-05-25 17:05 UTC, filip-szweda requested changes

2023-05-25 17:05 UTC, filip-szweda commented on entity/action/push/Push.gd
> +		# sometimes we might need to wait a few frames for wood to appear
A workaround, but it will do for now :)

2023-05-25 17:05 UTC, filip-szweda commented on entity/action/push/Push.gd
> +			pushed_object = Globals.WORLD_UPDATER.objects_container.get_node(str(pushed_object_id))
`get_object_by_id`

2023-05-25 17:49 UTC, Krystian030 approved these changes

2023-05-25 17:51 UTC, filip-szweda approved these changes
Good job :)

2023-05-25 17:51 UTC, merged