Lnx 126 add displaying tree object
group-project-gut/lynx-frontend-godot pull request #9
Opened 2023-05-06 14:31 UTC by Krystian030

- Add chop action
- Add create object action
- Add remove object action
- Add populate button

2023-05-07 11:02 UTC, filip-szweda requested changes

2023-05-07 11:02 UTC, filip-szweda commented on ui/Populate.gd
> +@onready var post_populate_endpoint_url = "http://127.0.0.1:8555/populate"
`SERVER_ADDRESS` + "populate"

2023-05-07 14:13 UTC, Krystian030 commented on ui/Populate.gd
> +@onready var post_populate_endpoint_url = "http://127.0.0.1:8555/populate"
Done

2023-05-07 14:13 UTC, Krystian030 commented on ui/CodeEditor.gd
> +	self.text = "move(Vector(1,0))\nchop(Vector(1,0))"
Done

2023-05-07 14:13 UTC, Krystian030 commented on ui/CodeEditor.gd
> -const keywords = ['dupa', 'and', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else',
Done

2023-05-07 14:13 UTC, Krystian030 commented on scene/world_updater/DeltasApplier.gd
> +		if not "_object_id" in entity:
Done

2023-05-07 14:14 UTC, Krystian030 commented on scene/world_updater/DeltasApplier.gd
> +			print(entity.name)
Done

2023-05-07 14:14 UTC, Krystian030 commented on entity/object/agent.tscn
> +animation = &"chop_down"
Done

2023-05-07 18:40 UTC, alpinus4 requested changes

2023-05-07 18:40 UTC, alpinus4 commented on ui/Populate.gd
> +extends Node
Please make populate button work on the same principles as creating agent button.
The UI node 
![image](https://user-images.githubusercontent.com/25907897/236695351-f188cbe2-f2b9-4a2a-a9ef-c2070f96790d.png)
should catch pressing populate button and emit custom signal.
![image](https://user-images.githubusercontent.com/25907897/236695323-e436d6aa-3afa-49bd-8b1c-72f72438b2db.png)
similarly as above.

Then in the scene you could create 'Populator'
or similarly named node.
![image](https://user-images.githubusercontent.com/25907897/236695388-e8126cf7-58c0-4b52-a1d9-7f84732828e4.png)
that would handle the logic of actually sending populate request.
Thanks to that we keep logic outside of UI.

2023-05-07 18:40 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +	print(">>>>>>>>>>>>>>>>>>> DELTAS <<<<<<<<<<<<<<<<<")
please remove prints here

2023-05-07 18:40 UTC, alpinus4 commented on scene/world_updater/DeltasApplier.gd
> +@onready var global_action_queue = get_node("../../GlobalActionQueue/Queue")
lets use get_owner() where possible
`get_owner().get_node("GlobalActionQueue/Queue")`

2023-05-07 18:40 UTC, alpinus4 commented on entity/object/tree/Tree.gd
> +# payload string used specifically for POST requests to scene-host
both functions 
`func to_payload_string(dict: Dictionary):`
and 
`func serialize():`
are not needed, please remove them

2023-05-07 18:40 UTC, alpinus4 commented on entity/action/remove_object/RemoveObject.gd
> +@onready var objects_container = get_node("../../../../ObjectsContainer")
The tree is as follows here
ObjectsContainer
-> Object
-> -> Queue
->->-> RemoveObjectAction

so change it to
```gdscript
@onready var objects_container = get_parent().get_parent().get_parent()
```

2023-05-07 18:40 UTC, alpinus4 commented on entity/action/create_object/CreateObject.gd
> +@onready var objects_container = get_node("../../../../ObjectsContainer")
This is inside global action queue. Thereof to access ObjectContainer we should get it from WorldUpdater.
```gdscript
@onready var objects_container = get_parent().get_parent().get_parent().objects_container
```

2023-05-08 21:04 UTC, Krystian030 commented on scene/world_updater/DeltasApplier.gd
> +	print(">>>>>>>>>>>>>>>>>>> DELTAS <<<<<<<<<<<<<<<<<")
done

2023-05-08 21:06 UTC, Krystian030 commented on scene/world_updater/DeltasApplier.gd
> +@onready var global_action_queue = get_node("../../GlobalActionQueue/Queue")
Done

2023-05-08 21:08 UTC, Krystian030 commented on entity/object/tree/Tree.gd
> +# payload string used specifically for POST requests to scene-host
done

2023-05-08 21:35 UTC, Krystian030 commented on entity/action/create_object/CreateObject.gd
> +@onready var objects_container = get_node("../../../../ObjectsContainer")
done

2023-05-08 21:35 UTC, Krystian030 commented on entity/action/remove_object/RemoveObject.gd
> +@onready var objects_container = get_node("../../../../ObjectsContainer")
done

2023-05-09 20:20 UTC, alpinus4 approved these changes
Looks good

2023-05-10 17:13 UTC, filip-szweda approved these changes

2023-05-10 17:14 UTC, merged